# -*- coding: utf-8 -*-
"""A job recommender system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17x4iHq3o-esX4cecvbe4R4d4W2_w99_z
"""

import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import nltk
import re
from nltk.corpus import stopwords
import string

data = pd.read_csv("jobs.csv")
print(data.head())

data = data.drop("Unnamed: 0",axis=1)

data.isnull().sum()

text = " ".join(i for i in data["Key Skills"])
stopwords = set(STOPWORDS)
wordcloud = WordCloud(stopwords=stopwords,
                      background_color="white").generate(text)
plt.figure( figsize=(15,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

text = " ".join(i for i in data["Functional Area"])
stopwords = set(STOPWORDS)
wordcloud = WordCloud(stopwords=stopwords,
                      background_color="white").generate(text)
plt.figure( figsize=(15,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

text = " ".join(i for i in data["Job Title"])
stopwords = set(STOPWORDS)
wordcloud = WordCloud(stopwords=stopwords,
                      background_color="white").generate(text)
plt.figure( figsize=(15,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer
feature = data["Key Skills"].tolist()
# Join the list of strings into a single string
text = " ".join(feature)
tfidf = TfidfVectorizer(input='content', stop_words="english") # Set input to 'content'
tfidf_matrix = tfidf.fit_transform([text]) # Pass the text as a list with a single element
similarity = cosine_similarity(tfidf_matrix)

indices = pd.Series(data.index, index=data['Job Title']).drop_duplicates()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
feature = data["Key Skills"].tolist()
text = " ".join(feature)

tfidf = TfidfVectorizer(input='content', stop_words="english")
tfidf_matrix = tfidf.fit_transform(feature)
similarity = cosine_similarity(tfidf_matrix)

indices = pd.Series(data.index, index=data['Job Title']).drop_duplicates()

def jobs_recommendation(Title, similarity = similarity):
    index = indices[Title]
    if similarity.ndim > 1:
        similarity = similarity.flatten()
    similarity_scores = list(enumerate(similarity[index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    similarity_scores = similarity_scores[0:5]
    newsindices = [i[0] for i in similarity_scores]
    return data[['Job Title', 'Job Experience Required',
                 'Key Skills']].iloc[newsindices]

print(jobs_recommendation("Software Developer"))